include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error rules
    always_use_package_imports: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_type_to_string: true
    empty_statements: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    
    # Style rules
    always_declare_return_types: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_unused_constructor_parameters: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_interpolation_to_compose_strings: true
    prefer_single_quotes: true
    sort_child_properties_last: true
    sort_constructors_first: true
    sort_unnamed_constructors_first: true
    unnecessary_const: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_this: true
    
    # Pub rules
    depend_on_referenced_packages: true
    package_names: true
    secure_pubspec_urls: true
    
    # Documentation rules
    package_api_docs: true
    public_member_api_docs: false

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  
  errors:
    # Treat missing required parameters as an error
    missing_required_param: error
    # Treat missing returns as an error
    missing_return: error
    # Treat invalid assignments as an error
    invalid_assignment: error
    # Treat using non-constant values as keys in literal maps as an error
    non_constant_map_key: error
    # Treat using deprecated members as a warning
    deprecated_member_use: warning
    # Treat dead code as a warning
    dead_code: warning
    
  exclude:
    - "lib/generated_plugin_registrant.dart"
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "test/.test_coverage.dart"
    - "bin/cache/**"
    - "lib/generated/**"

# Additional configurations
dart_code_metrics:
  metrics:
    cyclomatic-complexity: 20
    number-of-parameters: 4
    maximum-nesting-level: 5
  rules:
    - avoid-dynamic
    - avoid-passing-async-when-sync-expected
    - avoid-redundant-async
    - avoid-unnecessary-conditionals
    - no-boolean-literal-compare
    - prefer-trailing-comma
    - prefer-conditional-expressions
    - no-equal-then-else
  anti-patterns:
    - long-method
    - long-parameter-list
